import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Chatroom} from '../components/Chatroom'


export function getServerSideProps(ctx: any) {
  return {
    props: {
      room: ctx.query.room,
      user: ctx.query.user
    }
  }
}

const Chat: NextPage = (props: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className={styles.main}>
        <h2>{props.room}</h2>
        <Chatroom user={props.user} room={props.room}/>
      </main>
    </div>
  )
}

export default Chat;
